" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Fix backspace problem
set backspace=indent,eol,start

" Disable mouse
set mouse=
set ttymouse=

" Change cursor shape in different modes
let &t_SI = "\e[6 q" " Insert mode: Steady bar
let &t_SR = "\e[4 q" " Replace mode: Steady underline
let &t_EI = "\e[2 q" " Normal mode: Steady block

" Set colorscheme
colorscheme zaibatsu

" Enable type file detection. Vim will be able to try to detect the type of
" file in use.
filetype on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Load an indent file for the detected file type.
filetype indent on

" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number relativenumber

" Highlight cursor line underneath the cursor horizontally.
set cursorline

" Highlight cursor line underneath the cursor vertically.
set cursorcolumn

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4
set softtabstop=4

" Use space characters instead of tabs.
set expandtab

" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=5

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as
" you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
"set hlsearch
" Turn off highlighting completely
set nohlsearch

" Set the commands to save in history default number is 20.
set history=100

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Short-cutting split navigation, saving a keypress:
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Show margin at column 73, F4 key to toggle
"map <F4> :silent execute "set colorcolumn=" . (&colorcolumn == "" ? "73" : "")<CR>
" Show margin at column 80
set colorcolumn=80

" Spell check, F5 key to toggle
map <F5> :setlocal spell! spelllang=en_us<CR>

" Netrw (file manager)
map <F6> :Explore<CR>

" Remember and jump to last edit position
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
