#! /bin/sh

# autostart
xsetroot -cursor_name left_ptr
unclutter &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color     "#eb4129"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Alacritty state=floating

# Alert loop
while true; do
    # Battery Alert
    bat_cap=$(cat /sys/class/power_supply/BAT1/capacity)
    bat_stat=$(cat /sys/class/power_supply/BAT1/status)
	bat="[B:$bat_cap%$bat_stat]"
    if [[ $bat_cap -lt 10 ]] && [ $bat_stat = "Discharging" ]
    then
        notify-send -t 1000 -u critical "Battery Low"
    fi
	sleep 1s
done
